repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v0.7.0
  hooks:
  -   id: end-of-file-fixer
  -   id: check-json
  -   id: flake8
  -   id: check-merge-conflict
      language: python

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  -   id: isort
